/**
 * Flow: switch-between-alphabetical-and-label-view
 * Source: https://www.contentstack.com/docs/developers/create-content-types/switch-between-alphabetical-and-label-view
 * Generated/updated by bulkIngestFromUrls. Prefer data-test-id selectors.
 */

/** Label view: “All Labels” heading / control (switch to label list). */
export const SWITCH_VIEW_LABELS_LIST_TITLE_SELECTOR =
  "[data-test-id='cs-ct-labels-list-title'], .conttypelist-alllable [data-test-id='cs-ct-labels-list-title']";

/** Label view: list body — click opens a label bucket (automation uses first match). */
export const SWITCH_VIEW_LABELS_LIST_ELEMENTS_SELECTOR = "[data-test-id='cs-ct-labels-list-elements']";

export const CLICK_SELECTORS: Record<string, string> = {
  "All Labels (doc step)": SWITCH_VIEW_LABELS_LIST_TITLE_SELECTOR,
  "Any label from list (doc step)": SWITCH_VIEW_LABELS_LIST_ELEMENTS_SELECTOR,
  "cms button": "[data-test-id=\"cs-cms-button\"]",
  "TopNavbar__content__product__button svg logo": "[data-test-id=\"TopNavbar__content__product__button-svg-logo\"]",
  "ProductLogoHeadlessCMS": "[data-test-id=\"cs-icon\"]",
  "cms nav dashboard": "[data-test-id=\"cms-nav-dashboard\"]",
  "Dashboard": "[data-test-id=\"cs-icon\"]",
  "cms nav entries": "[data-test-id=\"cms-nav-entries\"]",
  "EntriesSecondary": "[data-test-id=\"cs-icon\"]",
  "cms nav assets": "[data-test-id=\"cms-nav-assets\"]",
  "AssetsSecondary": "[data-test-id=\"cs-icon\"]",
  "cms nav content models": "[data-test-id=\"cms-nav-content-models\"]",
  "ContentModel": "[data-test-id=\"cs-icon\"]",
  "cms nav publish queue": "[data-test-id=\"cms-nav-publish-queue\"]",
  "PublishQueue": "[data-test-id=\"cs-icon\"]",
  "cms nav releases": "[data-test-id=\"cms-nav-releases\"]",
  "Releases": "[data-test-id=\"cs-icon\"]",
  "cms nav tasks": "[data-test-id=\"cms-nav-tasks\"]",
  "Tasks": "[data-test-id=\"cs-icon\"]",
  "cms nav settings": "[data-test-id=\"cms-nav-settings\"]",
  "ProductSettings": "[data-test-id=\"cs-icon\"]",
  "select async": "[data-test-id=\"cs-select-async\"]",
  "cms nav apps": "[data-test-id=\"cms-nav-apps\"]",
  "AppSecondary": "[data-test-id=\"cs-icon\"]",
  "CaretDownNew": "[data-test-id=\"cs-icon\"]",
  "header search container": "[data-test-id=\"cs-header-search-container\"]",
  "header search icon": "[data-test-id=\"cs-header-search-icon\"]",
  "tooltip": "[data-test-id=\"cs-tooltip\"]",
  "Search": "[data-test-id=\"cs-icon\"]",
  "NotificationAlert": "[data-test-id=\"cs-notification-bell-icon\"]",
  "HelpExtraLarge": "[data-test-id=\"cs-help-center\"]",
  "app switcher": "[data-test-id=\"app-switcher\"]",
  "app switcher toolbar": "[data-test-id=\"app-switcher-toolbar\"]",
  "AppDrawer": "[data-test-id=\"cs-icon\"]",
  "user profile": "[data-test-id=\"cs-user-profile\"]",
  "breadcrumb": "[data-test-id=\"cs-breadcrumb\"]",
  "breadcrumb link 0": "[data-test-id=\"cs-breadcrumb-link-0\"]",
  "Stacks": "[data-test-id=\"cs-icon\"]",
  "truncate": "[data-test-id=\"cs-truncate\"]",
  "CaretRight": "[data-test-id=\"cs-icon\"]",
  "breadcrumb link 2": "[data-test-id=\"cs-breadcrumb-link-2\"]",
  "page layout": "[data-test-id=\"cs-page-layout\"]",
  "page layout header": "[data-test-id=\"cs-page-layout-header\"]",
  "page layout go back": "[data-test-id=\"cs-page-layout-go-back\"]",
  "LeftArrow": "[data-test-id=\"cs-icon\"]",
  "page header": "[data-test-id=\"cs-page-header\"]",
  "save content page title edit": "[data-test-id=\"cs-save-content-page-title-edit\"]",
  "ct edit icon": "[data-test-id=\"cs-ct-edit-icon\"]",
  "Edit": "[data-test-id=\"cs-icon\"]",
  "pill": "[data-test-id=\"cs-pill\"]",
  "pill item 0": "[data-test-id=\"cs-pill-item-0\"]",
  "pillIcon": "[data-test-id=\"pillIcon\"]",
  "SingleContentType": "[data-test-id=\"cs-icon\"]",
  "open fvr button": "[data-test-id=\"cs-open-fvr-button\"]",
  "fvr count title": "[data-test-id=\"cs-fvr-count-title\"]",
  "fvr count badge": "[data-test-id=\"cs-fvr-count-badge\"]",
  "save content page add label select": "[data-test-id=\"cs-save-content-page-add-label-select\"]",
  "sidebar window": "[data-test-id=\"cs-sidebar-window\"]",
  "save content page right sidebar information tab": "[data-test-id=\"cs-save-content-page-right-sidebar-information-tab\"]",
  "Information": "[data-test-id=\"cs-icon\"]",
  "entry edit tab widgets": "[data-test-id=\"cs-entry-edit-tab-widgets\"]",
  "Widgets": "[data-test-id=\"cs-icon\"]",
  "ct builder information": "[data-test-id=\"cs-ct-builder-information\"]",
  "Warning": "[data-test-id=\"cs-icon\"]",
  "content type editor learn more": "[data-test-id=\"cs-content-type-editor-learn-more\"]",
  "button": "[data-test-id=\"cs-button\"]",
  "CloseNoborder": "[data-test-id=\"cs-icon\"]",
  "ct field": "[data-test-id=\"cs-ct-field\"]",
  "ct title": "[data-test-id=\"cs-ct-title\"]",
  "ct title option move": "[data-test-id=\"cs-ct-title-option-move\"]",
  "ActionBar": "[data-test-id=\"cs-ct-title-option-move-icon\"]",
  "SingleLineText": "[data-test-id=\"cs-ct-title-icon\"]",
  "ct title truncate": "[data-test-id=\"cs-ct-title-truncate\"]",
  "ct title properties information": "[data-test-id=\"cs-ct-title-properties-information\"]",
  "ct title option properties": "[data-test-id=\"cs-ct-title-option-properties\"]",
  "Sliders": "[data-test-id=\"cs-icon\"]",
  "ct title option delete": "[data-test-id=\"cs-ct-title-option-delete\"]",
  "Delete": "[data-test-id=\"cs-icon\"]",
  "field type selector": "[data-test-id=\"cs-field-type-selector\"]",
  "PurpleAdd": "[data-test-id=\"cs-icon\"]",
  "empty state": "[data-test-id=\"cs-empty-state\"]",
  "empty state title": "[data-test-id=\"cs-empty-state-title\"]",
  "empty state desctiption": "[data-test-id=\"cs-empty-state-desctiption\"]",
  "empty state actions": "[data-test-id=\"cs-empty-state-actions\"]",
  "learn more link": "[data-test-id=\"cs-learn-more-link\"]",
  "button group": "[data-test-id=\"cs-button-group\"]",
  "ct save": "[data-test-id=\"cs-ct-save\"]",
  "Save": "[data-test-id=\"cs-icon\"]",
  "ct save close": "[data-test-id=\"cs-ct-save-close\"]",
  "ProductLogoHeadlessCMS (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"ProductLogoHeadlessCMS\"]",
  "Dashboard (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Dashboard\"]",
  "EntriesSecondary (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"EntriesSecondary\"]",
  "AssetsSecondary (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"AssetsSecondary\"]",
  "ContentModel (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"ContentModel\"]",
  "PublishQueue (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"PublishQueue\"]",
  "Releases (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Releases\"]",
  "Tasks (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Tasks\"]",
  "ProductSettings (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"ProductSettings\"]",
  "AppSecondary (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"AppSecondary\"]",
  "CaretDownNew (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"CaretDownNew\"]",
  "Search (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Search\"]",
  "NotificationAlert (icon)": "[data-test-id=\"cs-notification-bell-icon\"] svg[name=\"NotificationAlert\"]",
  "HelpExtraLarge (icon)": "[data-test-id=\"cs-help-center\"] svg[name=\"HelpExtraLarge\"]",
  "AppDrawer (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"AppDrawer\"]",
  "Stacks (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Stacks\"]",
  "CaretRight (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"CaretRight\"]",
  "LeftArrow (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"LeftArrow\"]",
  "Edit (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Edit\"]",
  "SingleContentType (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"SingleContentType\"]",
  "Information (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Information\"]",
  "Widgets (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Widgets\"]",
  "Warning (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Warning\"]",
  "CloseNoborder (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"CloseNoborder\"]",
  "ActionBar (icon)": "[data-test-id=\"cs-ct-title-option-move-icon\"] svg[name=\"ActionBar\"]",
  "SingleLineText (icon)": "[data-test-id=\"cs-ct-title-icon\"] svg[name=\"SingleLineText\"]",
  "Sliders (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Sliders\"]",
  "Delete (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Delete\"]",
  "PurpleAdd (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"PurpleAdd\"]",
  "Save (icon)": "[data-test-id=\"cs-icon\"] svg[name=\"Save\"]",
};

export const INPUT_SELECTORS: Record<string, string> = {
};
